### ISSUE TITLE
channels.list method that is called in Slack API is deprecated and being removed.  New apps cannot use it.

### ISSUE THREAD

**Issue by msiege2** [ServerlessOpsIO/aws-sns-to-slack-publisher#3]
Any Slack application created after June 10, 2020 is not allowed to make a call to `channels.list` in the Slack API.  This API will be disabled for ALL apps in Feb 2021.

Clients are asked to use `conversations.list` instead.

The change to the code for this project should be minimal, just making a call to a different endpoint.

See: https://api.slack.com/methods/channels.list

**Comment by tmclaugh** [comment]
Merged #4.

Thanks!
